global:
  enabled: true
  tlsDisable: false

server:
  ha:
    enabled: true
    replicas: 3
    apiAddr: "https://$(HOSTNAME).vault-internal:8200"
    clusterAddr: "https://$(HOSTNAME).vault-internal:8201"
    raft:
      enabled: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 0
          address = "0.0.0.0:8200"
          cluster_address = "0.0.0.0:8201"
          tls_cert_file = "/config/vault-tls/vault.crt"
          tls_key_file  = "/config/vault-tls/vault.key"
          tls_client_ca_file = "/config/vault-tls/ca.crt"
        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_tls_servername = "vault-0.vault-internal"
            leader_ca_cert_file = "/config/vault-tls/ca.crt"
            leader_client_cert_file = "/config/vault-tls/vault.crt"
            leader_client_key_file = "/config/vault-tls/vault.key"
          }

          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_tls_servername = "vault-1.vault-internal"
            leader_ca_cert_file = "/config/vault-tls/ca.crt"
            leader_client_cert_file = "/config/vault-tls/vault.crt"
            leader_client_key_file = "/config/vault-tls/vault.key"
          }

          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_tls_servername = "vault-2.vault-internal"
            leader_ca_cert_file = "/config/vault-tls/ca.crt"
            leader_client_cert_file = "/config/vault-tls/vault.crt"
            leader_client_key_file = "/config/vault-tls/vault.key"
          }
        }

        service_registration "kubernetes" {}
  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/data"
    storageClass: "local-path"
    accessMode: ReadWriteOnce

  volumes:
    - name: vault-tls
      secret:
        secretName: vault-tls
  volumeMounts:
    - name: vault-tls
      mountPath: /config/vault-tls

  extraEnvironmentVars:
    VAULT_API_ADDR: "https://$(HOSTNAME).vault-internal:8200"
    VAULT_CLUSTER_ADDR: "https://$(HOSTNAME).vault-internal:8201"
    VAULT_CACERT: "/config/vault-tls/ca.crt"

  service:
    type: ClusterIP

ui:
  enabled: true
  serviceType: ClusterIP